FROM debian:bullseye

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y --no-install-recommends \
        g++ \
        gcc \
        make \
        nasm \
        python3 \
        python3-distutils \
        scons
