FROM debian:bullseye

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y \
        acpica-tools \
        gcc \
        make \
        nasm \
        python3 \
        python3-distutils \
        scons
